[workspace]
members = [
    "shaku",
    "shaku_derive",
    "shaku_internals"
]

[patch.crates-io]
shaku = { path = "shaku" }
shaku_internals = { path = "shaku_internals" }
shaku_derive = { path = "shaku_derive" }
