version: 2.1
commands:
  remove-rust-toolchain:
    steps:
      - run:
          name: "Remove rust-toolchain"
          command: rm rust-toolchain
  install-tools:
    steps:
      - run:
          name: "Install Tools"
          command: rustup component add rustfmt clippy
  style-check:
    steps:
      - run:
          name: "Code Style Check"
          command: cargo fmt -- --check
  lint-check:
    steps:
      - run:
          name: "Code Lint Check"
          command: cargo clippy --all-targets --all-features -- -D clippy::all
  code-check:
    parameters:
      check-args:
        type: string
        default: ""
    steps:
      - run:
          name: "Cargo Check"
          command: cargo check --all << parameters.check-args >>
  test:
    parameters:
      test-args:
        type: string
        default: ""
    steps:
      - run:
          name: "Test"
          command: cargo test --all << parameters.test-args >>
jobs:
  shaku:
    docker:
      - image: rust:1.68.2
    steps:
      - checkout
      - remove-rust-toolchain
      - install-tools
      - style-check
      - lint-check
      - code-check
      - test
      - run:
          name: "Test with thread_safe off"
          working_directory: shaku
          command: cargo test --no-default-features --features derive -- --skip compile_fail
  shaku-msrv:
    docker:
      - image: rust:1.38.0
    steps:
      - checkout
      - remove-rust-toolchain
      - install-tools
      - run:
          name: "Use MSRV Cargo.lock"
          command: cp Cargo.lock.msrv Cargo.lock
      - run:
          # The web frameworks have a higher MSRV, and simply using --exclude doesn't always work since Cargo tries to
          # still build the dependency graph, but the old Cargo version can't parse some newer Cargo.toml files.
          name: "Remove crates from workspace that require newer Rust versions"
          command: sed -i -E '/shaku_actix|shaku_axum|shaku_rocket/d' Cargo.toml
      - code-check:
          check-args: "--locked"
      - test:
          # Skip compile tests, as compiler messages are different in 1.38.0.
          test-args: "--locked -- --skip compile_fail"
workflows:
  version: 2
  build:
    jobs:
      - shaku
      - shaku-msrv
