version: 2.1
commands:
  remove-rust-toolchain:
    steps:
      - run:
          name: "Remove rust-toolchain"
          command: rm rust-toolchain
  install-tools:
    steps:
      - run:
          name: "Install Tools"
          command: rustup component add rustfmt clippy
  style-check:
    steps:
      - run:
          name: "Code Style Check"
          command: cargo fmt -- --check
  lint-check:
    steps:
      - run:
          name: "Code Lint Check"
          command: cargo clippy --all-targets --all-features -- -D clippy::all
  code-check:
    steps:
      - run:
          name: "Cargo Check"
          command: cargo check
  test:
    parameters:
      test-args:
        type: string
        default: ""
    steps:
      - run:
          name: "Test"
          command: cargo test << parameters.test-args >>
jobs:
  shaku:
    docker:
      - image: rust:1.43.1
    steps:
      - checkout
      - remove-rust-toolchain
      - install-tools
      - style-check
      - lint-check
      - code-check
      - test
  shaku-msrv:
    docker:
      - image: rust:1.38.0
    steps:
      - checkout
      - remove-rust-toolchain
      - install-tools
      - code-check
      - test:
          # Multiple compiler messages are different in 1.38.0
          test-args: "-- --skip compile_fail"
  shaku_rocket:
    docker:
      - image: rust:1.43.1
    working_directory: ~/project/shaku_rocket
    steps:
      - checkout:
          path: ~/project
      - run:
          name: "Install Nightly Compiler"
          command: |
            # Use the default profile to automatically get a nightly with clippy and rustfmt
            rustup set profile default
            rustup default nightly
      - style-check
      - lint-check
      - code-check
      - test
workflows:
  version: 2
  build:
    jobs:
      - shaku
      - shaku-msrv
      - shaku_rocket
