version: 2.1
commands:
  remove-rust-toolchain:
    steps:
      - run:
          name: "Remove rust-toolchain"
          command: rm rust-toolchain
  install-tools:
    steps:
      - run:
          name: "Install Tools"
          command: rustup component add rustfmt clippy
  style-check:
    steps:
      - run:
          name: "Code Style Check"
          command: cargo fmt -- --check
  lint-check:
    steps:
      - run:
          name: "Code Lint Check"
          command: cargo clippy --all-targets --all-features -- -D clippy::all
  code-check:
    parameters:
      check-args:
        type: string
        default: ""
    steps:
      - run:
          name: "Cargo Check"
          command: cargo check --all << parameters.check-args >>
  test:
    parameters:
      test-args:
        type: string
        default: ""
    steps:
      - run:
          name: "Test"
          command: cargo test --all << parameters.test-args >>
jobs:
  shaku:
    docker:
      - image: rust:1.68.2
    steps:
      - checkout
      - remove-rust-toolchain
      - install-tools
      - style-check
      - lint-check
      - code-check
      - test
      - run:
          name: "Test with thread_safe off"
          working_directory: shaku
          command: cargo test --no-default-features --features derive -- --skip compile_fail
  shaku-msrv:
    docker:
      - image: rust:1.38.0
    steps:
      - checkout
      - remove-rust-toolchain
      - install-tools
      - run:
          name: "Use MSRV Cargo.lock"
          command: cp Cargo.lock.msrv Cargo.lock
      - code-check:
          # The web frameworks have a higher MSRV.
          check-args: "--locked --exclude shaku_actix --exclude shaku_rocket --exclude shaku_axum"
      - test:
          # Skip compile tests, as compiler messages are different in 1.38.0.
          test-args: "--locked --exclude shaku_actix --exclude shaku_rocket --exclude shaku_axum -- --skip compile_fail"
workflows:
  version: 2
  build:
    jobs:
      - shaku
      - shaku-msrv
