version: 2.1
commands:
  install-tools:
    steps:
      - run:
          name: "Install Tools"
          command: rustup component add rustfmt clippy
  style-check:
    steps:
      - run:
          name: "Code Style Check"
          command: cargo fmt -- --check
  lint-check:
    steps:
      - run:
          name: "Code Lint Check"
          command: cargo clippy --all-targets --all-features -- -D clippy::all
  code-check:
    steps:
      - run:
          name: "Cargo Check"
          command: cargo check
  test:
    steps:
      - run:
          name: "Test"
          command: cargo test
jobs:
  shaku:
    docker:
      - image: rust:1.41.0
    steps:
      - checkout
      - install-tools
      - style-check
      - lint-check
      - code-check
      - test
  shaku-msrv:
    docker:
      - image: rust:1.40.0
    steps:
      - checkout
      - install-tools
      - code-check
      - test
  shaku_rocket:
    docker:
      - image: rustlang/rust:nightly
    working_directory: ~/project/shaku_rocket
    steps:
      - checkout:
          path: ~/project
      - style-check
      - lint-check
      - code-check
      - test
workflows:
  version: 2
  build:
    jobs:
      - shaku
      - shaku-msrv
      - shaku_rocket
