[package]
name = "shaku"
version = "0.1.0"
authors = ["Mark <mark.drobnak@gmail.com>"]
description = "Dependency Injection for Rust"
repository = "https://github.com/Mcat12/shaku"
keywords = ["di", "ioc", "dependency", "inversion", "dependency-injection"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
shaku_derive = "~0.1.0"
shaku_internals = "~0.1.0"
anymap = "0.12.1"
log = "0.3"

[dev-dependencies]
rand = "0.7.2"

[features]
default = ["thread_safe"]

thread_safe = []